language: python

python: 
  - "3.6"

script: 
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t cjblink1/srtsignin-active-user-service-spike:$TRAVIS_COMMIT .
  - docker push cjblink1/srtsignin-active-user-service-spike:$TRAVIS_COMMIT